"""rename address

Revision ID: 4b49497fbde7
Revises: 766c4c2bcc91
Create Date: 2025-01-23 17:19:36.871518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b49497fbde7'
down_revision = '766c4c2bcc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
      op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
