"""rename department

Revision ID: 766c4c2bcc91
Revises: 0c71f51e8177
Create Date: 2025-01-23 17:04:01.389874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766c4c2bcc91'
down_revision = '0c71f51e8177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
